language: c++

#compiler:
#  - gcc
#  - clang

services:
  - docker

script:
  - INAM=cpuminer-rkz
  #- DOCKER_TAG=native
  #- OS=ubuntu
  #- VER=latest
  - CONF=
  - COIN=cpuchain
  #- CFLAGS="-g0 -Ofast -ffast-math -fassociative-math -freciprocal-math -fmerge-all-constants -fipa-pta -floop-nest-optimize -fgraphite-identity -floop-parallelize-all"
  - docker build                                 \
            -t innovanon/$INAM:$DOCKER_TAG       \
            --build-arg OS="$OS"                 \
            --build-arg VER="$VER"               \
            --build-arg REPO="$REPO"             \
            --build-arg DOCKER_TAG="$DOCKER_TAG" \
            --build-arg CONF="$CONF"             \
            --build-arg COIN="$COIN"             \
            --build-arg CFLAGS="$CFLAGS"         \
            .
  - docker run -d innovanon/$INAM:$DOCKER_TAG
  - sleep 60
  - docker ps -a
  # TODO
  - echo TODO testing/deploying
  - docker stop innovanon/$INAM:$DOCKER_TAG

