language: c++

#compiler:
#  - gcc
#  - clang

services:
  - docker

script:
  # test natively
  - docker build                                \
            -t innovanon/cpuminer-multi:native  \
            --build-arg COIN=neoscrypt          \
            --pull .
  - docker run -d innovanon/cpuminer-multi:native
  - sleep 19
  - docker ps -a
  - docker stop innovanon/cpuminer-multi:native
  # deploy generic
  - docker build                                \
            -t innovanon/cpuminer-multi:generic \
            --build-arg COIN=neoscrypt          \
            --pull .
  - docker run -d innovanon/cpuminer-multi:generic
  - sleep 19
  - docker ps -a
  - docker stop innovanon/cpuminer-multi:generic
  # TODO deploy

