version: '3.8'
services:
  cpuminer-neoscrypt:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/ghostlander/cpuminer-neoscrypt.git"
        CONF: "--enable-cpumining --disable-opencl --disable-adl"
        COIN: "neoscrypt"
    image: "innovanon/cpuminer-neoscrypt:${ARCH}"
  cpuminer-opt-cpupower:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/cpu-pool/cpuminer-opt-cpupower.git"
        CONF: ""
        COIN: "cpuchain"
    image: "innovanon/cpuminer-opt-cpupower:${ARCH}"
  cpuminer-opt-sugarchain:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/cryptozeny/cpuminer-opt-sugarchain.git"
        CONF: ""
        COIN: "sugarchain"
    image: "innovanon/cpuminer-opt-sugarchain:${ARCH}"
  cpuminer-opt:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/JayDDee/cpuminer-opt.git"
        CONF: ""
        COIN: "cpuchain"
    image: "innovanon/cpuminer-opt:${ARCH}"
  cpuminer-rkz:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/RickillerZ/cpuminer-RKZ.git"
        CONF: ""
        COIN: "cpuchain"
    image: "innovanon/cpuminer-rkz:${ARCH}"
  cpuminer-multi:
    build:
      context: .
      args:
        OS:   "ubuntu"
        VER:  "latest"
        REPO: "git://github.com/tpruvot/cpuminer-multi.git"
        CONF: ""
        COIN: "cpuchain"
    image: "innovanon/cpuminer-multi:${ARCH}"

