version: '3.8'
services:
  dockerhub:
    image: maccyber/micro-dockerhub-hook
    # build: .
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO
      # Path to docker-compose files who are triggered by scripts:
      # - /srv:/srv
    networks:
      dockerhub:
    secrets:
      - ssh_key
      - ssh_config
      - known_hosts
      #- source: ssh_key
      #  target: /root/.ssh/id_rsa
      ##- source: ssh_pub
      ##  target: /root/.ssh/id_rsa.pub

networks:
  dockerhub:

secrets:
  ssh_key:
    file: ./secrets/id_rsa
  ssh_config:
    file: ./secrets/config
  known_hosts:
    file: ./secrets/known_hosts
  #ssh_pub:
  #  file: ./secrets/id_rsa.pub

