version: 2.1

commands:
  build:
    parameters:
      os:
        default: "ubuntu"
        type: string
      ver:
        default: "latest"
        type: string
      mrep:
        type: string
      coin:
        default: "cpuchain"
        type: string
      docker_tag:
        default: "native"
        type: string
      conf:
        default: ""
        type: string
      inam:
        type: string
      flag:
        default: "-g0 -Ofast -ffast-math -fassociative-math -freciprocal-math -fmerge-all-constants -fipa-pta -floop-nest-optimize -fgraphite-identity -floop-parallelize-all"
        type: string
    steps:
      - checkout
      # TODO restore cache
      - run:
          name: Build
          command: |
            OS=<<parameters.os>>
            VER=<<parameters.ver>>
            INAM=<<parameters.inam>>
            REPO=<<parameters.mrep>>
            COIN=<<parameters.coin>>
            DOCKER_TAG=<<parameters.docker_tag>>
            CONF="<<parameters.conf>>"
            CFLAGS="<<parameters.flag>>"
            docker build                           \
              -t innovanon/$INAM:$DOCKER_TAG       \
              --build-arg OS="$OS"                 \
              --build-arg VER="$VER"               \
              --build-arg REPO="$REPO"             \
              --build-arg DOCKER_TAG="$DOCKER_TAG" \
              --build-arg CONF="$CONF"             \
              --build-arg COIN="$COIN"             \
              --build-arg CFLAGS="$CFLAGS"         \
              --pull .
      # TODO store cache
      - run:
          name: Test
          command: |
            INAM=<<parameters.inam>>
            DOCKER_TAG=<<parameters.docker_tag>>

            CID="`docker run -d --rm innovanon/$INAM:$DOCKER_TAG`"
            echo "CID=$CID"

            docker ps -a | grep "${CID::12}"
            sleep 99
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            docker ps -a | grep "${CID::12}"

            # TODO trigger dockerhub, don't build automatically
            echo TODO trigger dockerhub

            docker stop "$CID"

jobs:
  build-neoscrypt:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/ghostlander/cpuminer-neoscrypt.git"
          coin: "neoscrypt"
          inam: "cpuminer-neoscrypt"
  build-opt-cpupower:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cpu-pool/cpuminer-opt-cpupower.git"
          coin: "cpuchain"
          inam: "cpuminer-opt-cpupower"
  build-opt-sugarchain:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cryptozeny/cpuminer-opt-sugarchain.git"
          coin: "sugarchain"
          inam: "cpuminer-opt-sugarchain"
  build-rkz:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/RickillerZ/cpuminer-RKZ.git"
          inam: "cpuminer-rkz"
  build-opt:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/JayDDee/cpuminer-opt.git"
          coin: "yespower"
          inam: "cpuminer-opt"
  build-multi:
    machine:
      docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/tpruvot/cpuminer-multi.git"
          inam: "cpuminer-multi"

workflows:
  build-neoscrypt:
    jobs:
      - build-neoscrypt
  build-opt-cpupower:
    jobs:
      - build-opt-cpupower
  build-opt-sugarchain:
    jobs:
      - build-opt-sugarchain
  build-rkz:
    jobs:
      - build-rkz
  build-opt:
    jobs:
      - build-opt
#  build-multi:
#    jobs:
#      - build-multi

