version: 2.1

commands:
  build:
    parameters:
      #os:
      #  default: "ubuntu"
      #  type: string
      #ver:
      #  default: "latest"
      #  type: string
      mrep:
        type: string
      coin:
        default: "cpuchain"
        type: string
      docker_tag:
        default: "native"
        type: string
      #conf:
      #  default: ""
      #  type: string
      inam:
        type: string
      #flag:
      #  default: "-g0 -Ofast -ffast-math -fassociative-math -freciprocal-math -fmerge-all-constants -fipa-pta -floop-nest-optimize -fgraphite-identity -floop-parallelize-all"
      #  type: string
    steps:
      - checkout
      #- setup_remote_docker
      #- restore_cache:
      #    keys:
      #      - v1-{{ .Branch }}
      #    paths:
      #      - /caches/app.tar
      #- run:
      #    name: Load Docker image layer cache
      #    command: |
      #      docker load -i /caches/app.tar | :
      - run:
          name: Build
          command: |
            #OS=<<parameters.os>>
            #VER=<<parameters.ver>>
            INAM=<<parameters.inam>>
            REPO=<<parameters.mrep>>
            COIN=<<parameters.coin>>
            DOCKER_TAG=<<parameters.docker_tag>>
            #CONF="<<parameters.conf>>"
            #CFLAGS="<<parameters.flag>>"
            #docker build                           \
            #  --cache-from=app \
 
            docker build                           \
              -t innovanon/$INAM:$DOCKER_TAG       \
              --build-arg REPO="$REPO"             \
              --build-arg DOCKER_TAG="$DOCKER_TAG" \
              --build-arg COIN="$COIN"             \
              --pull .
      #- run:
      #    name: Save Docker image layer cache
      #    command: |
      #      mkdir -p /caches
      #      docker save -o /caches/app.tar app
      #- save_cache:
      #    key: v1-{{ .Branch }}-{{ epoch }}
      #    paths:
      #      - /caches/app.tar
      - run:
          name: Test
          command: |
            INAM=<<parameters.inam>>
            DOCKER_TAG=<<parameters.docker_tag>>
            [[ "$DOCKER_TAG" = native  ]] ||
            [[ "$DOCKER_TAG" = generic ]] ||
            exit 0

            CID="`docker run -d --rm innovanon/$INAM:$DOCKER_TAG`"
            echo "CID=$CID"

            docker ps -a | grep "${CID::12}"
            sleep 99
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            #docker ps -a | grep "${CID::12}"
            #sleep 19
            docker ps -a | grep "${CID::12}"

            # TODO trigger dockerhub, don't build automatically
            echo TODO trigger dockerhub

            docker stop "$CID"

jobs:
  build-neoscrypt:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/ghostlander/cpuminer-neoscrypt.git"
          coin: "neoscrypt"
          inam: "cpuminer-neoscrypt"
  build-neoscrypt-ppc4750:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/ghostlander/cpuminer-neoscrypt.git"
          coin: "neoscrypt"
          inam: "cpuminer-neoscrypt"
          docker_tag: "ppc4750"
      # TODO push to dockerhub
  build-neoscrypt-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/ghostlander/cpuminer-neoscrypt.git"
          coin: "neoscrypt"
          inam: "cpuminer-neoscrypt"
          docker_tag: "generic"
      # TODO push to dockerhub
  build-opt-cpupower:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cpu-pool/cpuminer-opt-cpupower.git"
          coin: "cpuchain"
          inam: "cpuminer-opt-cpupower"
  build-opt-cpupower-nehalem:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cpu-pool/cpuminer-opt-cpupower.git"
          coin: "cpuchain"
          inam: "cpuminer-opt-cpupower"
          docker_tag: "nehalem"
      # TODO push to dockerhub
  build-opt-cpupower-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cpu-pool/cpuminer-opt-cpupower.git"
          coin: "cpuchain"
          inam: "cpuminer-opt-cpupower"
          docker_tag: "generic"
      # TODO push to dockerhub
  build-opt-sugarchain:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cryptozeny/cpuminer-opt-sugarchain.git"
          coin: "sugarchain"
          inam: "cpuminer-opt-sugarchain"
  build-opt-sugarchain-nocona:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cryptozeny/cpuminer-opt-sugarchain.git"
          coin: "sugarchain"
          inam: "cpuminer-opt-sugarchain"
          docker_tag: "nocona"
      # TODO push to dockerhub
  build-opt-sugarchain-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/cryptozeny/cpuminer-opt-sugarchain.git"
          coin: "sugarchain"
          inam: "cpuminer-opt-sugarchain"
          docker_tag: "generic"
      # TODO push to dockerhub
  build-rkz:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/RickillerZ/cpuminer-RKZ.git"
          inam: "cpuminer-rkz"
  build-rkz-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/RickillerZ/cpuminer-RKZ.git"
          inam: "cpuminer-rkz"
          docker_tag: "generic"
      # TODO push to dockerhub
  build-opt:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/JayDDee/cpuminer-opt.git"
          coin: "yespower"
          inam: "cpuminer-opt"
  build-opt-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/JayDDee/cpuminer-opt.git"
          coin: "yespower"
          inam: "cpuminer-opt"
          docker_tag: "generic"
      # TODO push to dockerhub
  build-multi:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/tpruvot/cpuminer-multi.git"
          inam: "cpuminer-multi"
  build-multi-generic:
    machine: true
      #docker_layer_caching: true
    steps:
      - build:
          mrep: "git://github.com/tpruvot/cpuminer-multi.git"
          inam: "cpuminer-multi"
          docker_tag: "generic"
      # TODO push to dockerhub

workflows:
  build-neoscrypt:
    jobs:
      - build-neoscrypt
      - build-neoscrypt-generic
      #- build-neoscrypt-ppc4750
  build-opt-cpupower:
    jobs:
      - build-opt-cpupower
      - build-opt-cpupower-generic
      #- build-opt-cpupower-nehalem
  build-opt-sugarchain:
    jobs:
      - build-opt-sugarchain
      - build-opt-sugarchain-generic
      #- build-opt-sugarchain-nocona
  build-rkz:
    jobs:
      - build-rkz
      - build-rkz-generic
  build-opt:
    jobs:
      - build-opt
      - build-opt-generic
#  build-multi:
#    jobs:
#      - build-multi
#      - build-multi-generic

